version: '2'
services:
  app:
    build:
      context: ./
      dockerfile: docker/app/Dockerfile
      args:
        JSPM_GITHUB_AUTH_TOKEN: $JSPM_GITHUB_AUTH_TOKEN
    image: 'app:latest'
    restart: always
    volumes:
     - ./:/opt/app
     - /opt/app/node_modules
     - /opt/app/client/jspm_packages
    links:
     - db
  db:
    image: postgres:9.5
    restart: always
    ports:
      - "5432:5432"
    environment:
      POSTGRES_USER: $POSTGRES_USER
      POSTGRES_PASSWORD: $POSTGRES_PASSWORD
    volumes:
      - /opt/app/data:/var/lib/postgresql/data
  web:
    build:
      context: .
      dockerfile: docker/nginx/Dockerfile
    restart: always
    volumes:
     - ./client/dist:/usr/share/html
    links:
        - app:app
    ports:
        - "80:80"
  
  
  
