version: '2'
services:
  app:
    build: .
    entrypoint: ["./dev-entrypoint.sh"]
    ports:
     - "3000:3000"
     - "5858:5858"
    environment:
      NODE_ENV: development
      JSPM_GITHUB_AUTH_TOKEN: $JSPM_GITHUB_AUTH_TOKEN

