version: '2'
services:
  server:
    command: ["gulp"]
    links:
     - db
    ports:
     - "3000:3000"
     - "5858:5858"
     - "49152:49152"
     - "4200:4200"
    environment:
      NODE_ENV: development

